set (SRC 
  "b2DrawSFML.cpp"
  "imGuiDebug.cpp"
    )

set(HEADER
     "${RyuPrototype_SOURCE_DIR}/include/Ryu/Debug/b2DrawSFML.hpp"
     "${RyuPrototype_SOURCE_DIR}/include/Ryu/Debug/imGuiDebug.h"
)

add_library(ryudebuglib STATIC "${SRC}" "${HEADER}")

target_include_directories(ryudebuglib PUBLIC "${nlohmann_json_SOURCE_DIR}/include") 
target_include_directories(ryudebuglib PUBLIC "${RyuPrototype_SOURCE_DIR}/include")
target_include_directories(ryudebuglib PUBLIC "${box2d_SOURCE_DIR}/include") 
target_include_directories(ryudebuglib PUBLIC "${fmt_SOURCE_DIR}/include") 
target_include_directories(ryudebuglib PUBLIC "${imgui_SOURCE_DIR}/") 
link_sfml_to_target(ryudebuglib)
